"""Protocol/identity tests use explicit wire fixtures, never claimed live hardware."""
import math
from pathlib import Path
import random
import struct
import tempfile
import unittest
from unittest.mock import patch

from spatial.core import Engine
from spatial.pose import Quaternion
from spatial.trackers.common import EngineSource
from spatial.trackers.hid import inventory, sony_candidate, slime_candidate
from spatial.trackers.slime import AXES_OFFSET, Decoder, decode_rotation
from spatial.trackers.sony import (TimestampedDecoder, decode_pose, supported_layout,
                                   supported_angular_velocity)


ADDRESS = "AA:BB:CC:DD:EE:FF"
HARDWARE = "71C391F2ABCD"


def registration(slot=2, hardware=HARDWARE):
    return bytes((255, slot)) + int(hardware, 16).to_bytes(6, "little") + bytes(8)


def orientation(slot=2, xyzw=(0, 0, 0, 32767), packet_type=1):
    return struct.pack("<BB4h6x", packet_type, slot, *xyzw)


def sony_descriptor():
    # Source decoder's required logical/physical scale and 14-byte input report.
    return (b"\x05\x20\x09\xe1\xa1\x01\x85\x01\x75\x10\x95\x03"
            + b"\x16" + (-32767).to_bytes(2, "little", signed=True)
            + b"\x26" + (32767).to_bytes(2, "little")
            + b"\x37" + (-314159264).to_bytes(4, "little", signed=True)
            + b"\x47" + (314159265).to_bytes(4, "little")
            + b"\x55\x08\x81\x02\x75\x08\x95\x07\x81\x02\xc0")


def sony_timing_descriptor():
    return (sony_descriptor()[:-7]
            + b"\x0a\x45\x05\x35\xe0\x45\x20\x55\x00\x81\x02"
            + b"\x0a\x46\x05\x16\x00\x00\x26\xff\x00"
            + b"\x35\x00\x45\x00\x75\x08\x95\x01\x81\x02\xc0")


def timestamped_sony(captured=1_000_000_000, sequence=1, orientation=(0, 0, 0),
                     gyro=(0, 0, 0), discontinuity=0):
    return b"SPT1" + struct.pack("<QQB6hB", captured, sequence, 1,
                                *orientation, *gyro, discontinuity)


class IdentityTests(unittest.TestCase):
    def test_sysfs_binds_only_selected_bluetooth_sensor(self):
        with tempfile.TemporaryDirectory() as tmp:
            for number, bus, unique, descriptor in [
                (0, "0005", ADDRESS.lower(), sony_descriptor()),
                (1, "0005", "11:22:33:44:55:66", sony_descriptor()),
                (2, "0003", ADDRESS, sony_descriptor()),
                (3, "0005", ADDRESS, b"\x05\x01")]:
                path = Path(tmp) / f"hidraw{number}" / "device"
                path.mkdir(parents=True)
                (path / "uevent").write_text(
                    f"HID_ID={bus}:0000054C:00000DF1\nHID_UNIQ={unique}\nHID_NAME=WF-1000XM5\n")
                (path / "report_descriptor").write_bytes(descriptor)
            devices = inventory(tmp, "/test-dev")
            chosen = [device for device in devices if sony_candidate(device, ADDRESS)]
            self.assertEqual([device.path for device in chosen], ["/test-dev/hidraw0"])
            self.assertEqual(chosen[0].name, "WF-1000XM5")

    def test_receiver_discovery_requires_verified_product(self):
        from spatial.trackers.hid import HidDevice
        def device(vendor, product, bus=3):
            return HidDevice("/dev/test", Path("/test"), bus, vendor, product, "", "")
        for vendor, product in [(0x1209, 0x7690), (0x1209, 0x7692),
                                (0x4E76, 0xD2D0), (0x4E76, 0xD2DF)]:
            self.assertTrue(slime_candidate(device(vendor, product)))
        self.assertFalse(slime_candidate(device(0x1209, 0x7691)))
        self.assertFalse(slime_candidate(device(0x4E76, 0xD2E0)))
        self.assertFalse(slime_candidate(device(0x1209, 0x7690, bus=5)))


class SonyTests(unittest.TestCase):
    def test_descriptor_layout_is_checked_not_only_android_marker(self):
        desc = sony_descriptor()
        self.assertTrue(supported_layout(desc))
        self.assertFalse(supported_layout(desc.replace(b"\x75\x10", b"\x75\x20")))
        self.assertFalse(supported_layout(desc.replace(b"\x55\x08", b"\x55\x00")))
        self.assertFalse(supported_layout(desc[:-6]))
        self.assertFalse(supported_layout(b"\x05\x20\x09\xe1"))

    def test_absolute_zyx_inverse_and_canonical_axis_mapping(self):
        sine = math.sqrt(0.5)
        for angles, expected in [
                ((90, 0, 0), (sine, 0, -sine, 0)),
                ((0, 90, 0), (sine, sine, 0, 0)),
                ((0, 0, 90), (sine, 0, 0, sine))]:
            actual = decode_pose(struct.pack("=6d", 0, 0, 0, *angles))
            for left, right in zip(actual.values(), expected):
                self.assertAlmostEqual(left, right)

    def test_absolute_android_reports_preserve_physical_axes_and_nonidentity_recenter(self):
        # Signed int16 Android report vectors -> upstream UDP yaw/pitch/roll.
        # Euler fixtures were generated by compiling the actual scale/remap/
        # rotvec/Euler functions from the checksummed SonyTrackerLinux 1.0.0
        # main.c/quat.h used by our package, bypassing its startup reference
        # as --absolute does. No physical HID is simulated here.
        fixtures = [
            ((0, 0, 0), (-2.864788982816089e-07, 2.8647889684921435e-07, -2.864788982816089e-07)),
            ((8192, 0, 0), (-5.158573609289507e-07, 45.00137349636183, -5.158573609289507e-07)),
            ((0, 8192, 0), (-3.647574937444709e-07, 1.5108237880732272e-07, -45.00137349636184)),
            ((0, 0, 8192), (-45.00137349636184, 1.5108237880732272e-07, -3.647574937444709e-07)),
            ((4500, -7200, 11300), (-57.39880217484175, 39.13186620282233, 22.554859472203148)),
            ((6500, -8300, 4100), (-7.243522017445608, 40.5180541771601, 45.0231571600681)),
            ((-4300, 12000, 9000), (-31.36309781754969, -43.25427657295948, -58.32143328376762)),
            ((-12000, 9000, 6000), (5.868174261500792, -70.90508398608317, -61.36441996294061)),
            ((7000, 16000, -5000), (-9.684566868121523, 41.55780674758346, -96.24659087025287)),
        ]

        def multiply(a, b):
            return [[sum(a[i][k] * b[k][j] for k in range(3)) for j in range(3)]
                    for i in range(3)]

        def transpose(a):
            return list(zip(*a))

        def head_to_world(report):
            # Android's active rotation of the reference frame into the head
            # frame describes orientation, not world-vector -> head-vector
            # coordinates. Independent Rodrigues math avoids the helper map.
            vector = [(-314159264 + (v + 32767) / 65534 * 628318529) * 1e-8
                      for v in report]
            angle = math.hypot(*vector)
            x, y, z = (v / angle for v in vector)
            skew = ((0, -z, y), (z, 0, -x), (-y, x, 0))
            square = multiply(skew, skew)
            return [[float(i == j) + math.sin(angle) * skew[i][j]
                     + (1 - math.cos(angle)) * square[i][j] for j in range(3)]
                    for i in range(3)]

        # Android right/forward/up -> canonical right/up/back.
        basis = ((1, 0, 0), (0, 0, 1), (0, -1, 0))
        def assert_matrix(pose, expected):
            w, x, y, z = pose.values()
            actual = ((1 - 2*y*y - 2*z*z, 2*x*y - 2*w*z, 2*x*z + 2*w*y),
                      (2*x*y + 2*w*z, 1 - 2*x*x - 2*z*z, 2*y*z - 2*w*x),
                      (2*x*z - 2*w*y, 2*y*z + 2*w*x, 1 - 2*x*x - 2*y*y))
            for actual_row, expected_row in zip(actual, expected):
                for value, target in zip(actual_row, expected_row):
                    self.assertAlmostEqual(value, target, places=12)

        poses = {}
        for report, angles in fixtures:
            with self.subTest(report=report):
                poses[report] = decode_pose(struct.pack("=6d", 0, 0, 0, *angles))
                expected = multiply(multiply(basis, head_to_world(report)), transpose(basis))
                assert_matrix(poses[report], expected)

        # Start the real policy engine at a nonidentity absolute orientation,
        # then recenter at another combined orientation. Both operations must
        # produce reference^-1 * current, never current * reference^-1.
        engine = Engine()
        engine.connect(ADDRESS)
        source = EngineSource(engine)
        reference = (6500, -8300, 4100)
        source.sample(ADDRESS, "WF-1000XM5 fixture", "earbud", poses[reference])
        engine.set_enabled(ADDRESS, True)
        engine.select()
        assert_matrix(engine.pose, ((1, 0, 0), (0, 1, 0), (0, 0, 1)))
        for current in ((-4300, 12000, 9000), (7000, 16000, -5000)):
            source.sample(ADDRESS, "WF-1000XM5 fixture", "earbud", poses[current])
            relative = multiply(transpose(head_to_world(reference)), head_to_world(current))
            expected = multiply(multiply(basis, relative), transpose(basis))
            assert_matrix(engine.pose, expected)
            engine.recenter_active()
            reference = current
            assert_matrix(engine.pose, ((1, 0, 0), (0, 1, 0), (0, 0, 1)))

    def test_rejects_truncated_nonfinite_and_wrong_units(self):
        for packet in (b"\0" * 47, b"\0" * 49,
                       struct.pack("=6d", 0, 0, 0, float("nan"), 0, 0),
                       struct.pack("=6d", 0, 0, 0, 900, 0, 0)):
            with self.assertRaises(ValueError):
                decode_pose(packet)


class SonyTimestampTests(unittest.TestCase):
    def test_descriptor_checks_gyro_usage_scale_and_offsets_not_inherited_unit(self):
        descriptor = sony_timing_descriptor()
        self.assertTrue(supported_layout(descriptor))
        self.assertTrue(supported_angular_velocity(descriptor))
        # The Android usage mandates rad/s, independent of inherited HID Unit.
        self.assertTrue(supported_angular_velocity(descriptor.replace(
            b"\x0a\x45\x05", b"\x66\x01\x10\x0a\x45\x05")))
        for changed in (sony_descriptor(),
                        descriptor.replace(b"\x0a\x45\x05", b"\x0a\x44\x05"),
                        descriptor.replace(b"\x35\xe0", b"\x35\xdf"),
                        descriptor.replace(b"\x55\x00", b"\x55\x01")):
            self.assertFalse(supported_angular_velocity(changed))

    def test_direct_raw_axes_match_absolute_helper_and_preserve_zero_gyro(self):
        # Independently compiled upstream Euler fixtures are already checked
        # against Rodrigues matrices above. Raw decoding must reach those poses.
        fixtures = [((8192, 0, 0), (-5.158573609289507e-07, 45.00137349636183, -5.158573609289507e-07)),
                    ((0, 8192, 0), (-3.647574937444709e-07, 1.5108237880732272e-07, -45.00137349636184)),
                    ((0, 0, 8192), (-45.00137349636184, 1.5108237880732272e-07, -3.647574937444709e-07)),
                    ((6500, -8300, 4100), (-7.243522017445608, 40.5180541771601, 45.0231571600681))]
        for raw, angles in fixtures:
            decoder = TimestampedDecoder(angular_velocity_verified=True)
            packet = timestamped_sony(orientation=raw, discontinuity=255)
            actual, timing = decoder.feed(packet, 1_002_000_000)
            expected = decode_pose(struct.pack("=6d", 0, 0, 0, *angles))
            for value, target in zip(actual.values(), expected.values()):
                self.assertAlmostEqual(value, target, places=12)
            self.assertEqual(timing, {"captured_ns": 1_000_000_000, "received_ns": 1_002_000_000,
                                     "sequence": 1, "angular_velocity": (0., 0., 0.),
                                     "discontinuity": 255, "raw_report_hex": packet[20:].hex(),
                                     "clock": "host-monotonic"})

    def test_gyro_body_axes_require_descriptor_verification(self):
        packet = timestamped_sony(gyro=(32767, -16384, 8192))
        _, unverified = TimestampedDecoder().feed(packet, 1_002_000_000)
        self.assertIsNone(unverified["angular_velocity"])
        _, verified = TimestampedDecoder(angular_velocity_verified=True).feed(packet, 1_002_000_000)
        self.assertEqual(verified["angular_velocity"], (32., 8192 * 32 / 32767, 16384 * 32 / 32767))

    def test_rejects_invalid_packets_without_poisoning_next_sample(self):
        packet = timestamped_sony()
        malformed = [packet[:-1], packet + b"\0", b"SPT2" + packet[4:],
                     packet[:20] + b"\x02" + packet[21:],
                     timestamped_sony(captured=0), timestamped_sony(sequence=0),
                     timestamped_sony(captured=2_000_000_000),
                     timestamped_sony(captured=499_999_999),
                     timestamped_sony(sequence=2**63),
                     timestamped_sony(orientation=(-32768, 0, 0)),
                     timestamped_sony(orientation=(32767, 32767, 0)),
                     timestamped_sony(gyro=(-32768, 0, 0))]
        for bad in malformed:
            decoder = TimestampedDecoder(angular_velocity_verified=True)
            with self.subTest(packet=bad.hex()):
                with self.assertRaises(ValueError):
                    decoder.feed(bad, 1_000_000_000)
                _, timing = decoder.feed(packet, 1_000_000_000)
                self.assertEqual(timing["sequence"], 1)

    def test_duplicate_reordered_and_delayed_packets_never_refresh_pose(self):
        decoder = TimestampedDecoder()
        decoder.feed(timestamped_sony(sequence=2), 1_010_000_000)
        for captured, sequence in ((1_000_000_000, 2), (1_000_000_001, 2),
                                   (999_999_999, 3), (1_000_000_001, 1)):
            with self.assertRaises(ValueError):
                decoder.feed(timestamped_sony(captured=captured, sequence=sequence), 1_010_000_001)
        with self.assertRaises(ValueError):
            decoder.feed(timestamped_sony(captured=1_000_000_001, sequence=3), 1_009_999_999)
        # Packet loss and the uint8 sensor reference counter wrap are preserved,
        # so the predictor can reset rather than treating either as smooth motion.
        _, timing = decoder.feed(timestamped_sony(captured=1_020_000_000, sequence=4,
                                                 discontinuity=255), 1_021_000_000)
        self.assertEqual(timing["sequence"], 4)
        _, timing = decoder.feed(timestamped_sony(captured=1_030_000_000, sequence=5,
                                                 discontinuity=0), 1_031_000_000)
        self.assertEqual(timing["discontinuity"], 0)


class SlimeTests(unittest.TestCase):
    def test_identity_is_receiver_reported_address_not_slot_or_alias(self):
        decoder = Decoder()
        self.assertEqual(decoder.feed(orientation()), [])
        self.assertTrue(decoder.unknown_rotation)
        self.assertEqual(decoder.feed(registration()), [])
        event, = decoder.feed(orientation())
        self.assertEqual(event.hardware_id, HARDWARE)
        self.assertEqual(event.key, "slime:" + HARDWARE)
        self.assertEqual(event.action, "sample")

    def test_reregistration_never_creates_or_refreshes_pose(self):
        decoder = Decoder()
        self.assertEqual(decoder.feed(registration() * 4), [])
        self.assertEqual(decoder.feed(bytes((3, 2, 1)) + bytes(13)), [])
        self.assertEqual(decoder.feed(bytes((0, 2)) + bytes(14)), [])

    def test_receiver_slot_reuse_removes_only_previous_identity(self):
        decoder = Decoder()
        decoder.feed(registration())
        removed, = decoder.feed(registration(hardware="010203040506"))
        self.assertEqual((removed.action, removed.hardware_id), ("remove", HARDWARE))
        sample, = decoder.feed(orientation())
        self.assertEqual(sample.hardware_id, "010203040506")

    def test_disconnect_error_and_unpaired_identity_remove_tracker(self):
        for frame in (bytes((3, 2, 0)) + bytes(13),
                      bytes((3, 2, 3)) + bytes(13),
                      registration(hardware="000000000000")):
            decoder = Decoder()
            decoder.feed(registration())
            event, = decoder.feed(frame)
            self.assertEqual(event.action, "remove")

    def test_q15_and_compressed_packets_match_upstream_axes(self):
        for packet_type in (1, 4):
            q = decode_rotation(orientation(packet_type=packet_type))
            for actual, expected in zip(q.values(), AXES_OFFSET.values()):
                self.assertAlmostEqual(actual, expected)
        # nRF exp-map identity: quantization origin is 512,1024,1024.
        packed = 512 | (1024 << 10) | (1024 << 21)
        for packet_type in (2, 7):
            packet = bytes((packet_type, 2)) + bytes(3) + struct.pack("<I", packed) + bytes(7)
            q = decode_rotation(packet)
            for actual, expected in zip(q.values(), AXES_OFFSET.values()):
                self.assertAlmostEqual(actual, expected)

    def test_corrupt_quaternion_is_not_normalized_into_valid_data(self):
        decoder = Decoder()
        decoder.feed(registration())
        self.assertEqual(decoder.feed(orientation(xyzw=(0, 0, 0, 0))), [])
        self.assertEqual(decoder.feed(orientation(xyzw=(32767,) * 4)), [])
        self.assertEqual(decoder.feed(bytes((2, 2)) + bytes(14)), [])
        self.assertEqual(decoder.invalid_packets, 3)

    def test_malformed_reports_do_not_escape_parser(self):
        decoder = Decoder()
        generator = random.Random(104)
        for length in range(260):
            decoder.feed(generator.randbytes(length))
        self.assertEqual(decoder.feed(bytes(4112)), [])


class ProviderOwnershipTests(unittest.TestCase):
    def test_real_sample_creates_row_timeout_hides_it_and_off_is_non_destructive(self):
        engine = Engine()
        source = EngineSource(engine)
        with patch("spatial.trackers.common.time.monotonic", return_value=10):
            source.sample("slime:" + HARDWARE, HARDWARE, "optional", AXES_OFFSET)
        row, = engine.snapshot()["optional_trackers"]
        self.assertEqual(row["name"], HARDWARE)
        engine.set_enabled(row["id"], False)
        self.assertEqual(len(engine.trackers), 1)
        engine.advance(10.51)
        self.assertEqual(engine.snapshot()["optional_trackers"], [])

    def test_late_earbud_sample_after_disconnect_does_not_announce(self):
        engine = Engine()
        engine.connect(ADDRESS)
        source = EngineSource(engine)
        with patch("spatial.trackers.common.time.monotonic", return_value=10):
            source.sample(ADDRESS, "WF-1000XM5", "earbud", AXES_OFFSET)
            engine.disconnect()
            self.assertFalse(source.sample(ADDRESS, "WF-1000XM5", "earbud", AXES_OFFSET))
        self.assertEqual(engine.trackers, {})

    def test_old_session_cleanup_cannot_remove_new_provider(self):
        engine = Engine()
        old, new = EngineSource(engine), EngineSource(engine)
        with patch("spatial.trackers.common.time.monotonic", return_value=10):
            old.sample("slime:" + HARDWARE, HARDWARE, "optional", AXES_OFFSET)
            new.sample("slime:" + HARDWARE, HARDWARE, "optional", AXES_OFFSET)
        old.clear()
        self.assertEqual(len(engine.snapshot()["optional_trackers"]), 1)
        new.clear()
        self.assertEqual(engine.snapshot()["optional_trackers"], [])
