wireplumber.components = [
  {
    name = spatial-live-guard.lua
    type = script/lua
    provides = hooks.spatiald.live-guard
    requires = [ support.lua-scripting metadata.default ]
  }
]

wireplumber.profiles = {
  main = {
    hooks.spatiald.live-guard = required
  }
}
